### ISSUE TITLE
Build Module Error - Solution

### ISSUE THREAD

**Issue by yozef** [kosso/TiAdobeCreativeSDK#1]
Here are the Steps I took:
1- Downloaded the master repo
2- Downloaded the SDK from https://creativesdk.adobe.com/downloads.html
3- Copy/Pasted the `AdobeCreativeSDKFoundation.framework` & `AdobeCreativeSDKImage.framework` into the `MasterRepo/iPhone`:
![screen shot 2015-02-17 at 9 25 03 am](https://cloud.githubusercontent.com/assets/287256/6229648/ec986efc-b686-11e4-8067-0c62cb28ff9e.png)
4- Copy/Pasted the `AdobeCreativeSDKFoundationResources.bundle` and `AdobeCreativeSDKImageResources.bundle` into `.../myTitaniumWorkSpace/TiAdobeCreativeSDK/iphone`
5- Updated module.config: (on line 28) to: OTHER_LDFLAGS=$(inherited) -F".../myTitaniumWorkSpace/TiAdobeCreativeSDK/iphone" -framework AdobeCreativeSDKFoundation -framework AdobeCreativeSDKImage -ObjC
6- Opened Terminal: 
$> cd MasterRepo/iphone
$> python ./build.py
Result: 
[WARN] please update the manifest key: 'license' to a non-default value
[WARN] please update the LICENSE file with your license text before distributing
Traceback (most recent call last):
  File "./build.py", line 263, in <module>
    build_module(manifest,config)
  File "./build.py", line 174, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools
7- Updated `manifest` line 10 from `license: Specify your license` to  `license: MIT` (just to change the value) & LICENSE file with `Some Distribution License`
8- Ran build.py again...
Result:
Traceback (most recent call last):
  File "./build.py", line 263, in <module>
    build_module(manifest,config)
File "./build.py", line 174, in build_module
    from tools import ensure_dev_path
9 - Obviously it couldn't find the Ti SDK, so reopening the titanium.xcconfig, and noticed a ~ was missing, so on line 13 I simply added the `~`:
TITANIUM_SDK = ~/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA

and now it built properly :+1:

**Comment by kosso** [comment]
:+1: 

Thanks for explaining it a bit better than I did ;) 
Yes, everyone seems to have a slightly different installation setup of their Ti.SDK. 

Also the limitations on filesizes on Github meant that couldn't push the frameworks up too.
