### ISSUE TITLE
methods from Aviary

### ISSUE THREAD

**Issue by bwilhelm** [kosso/TiAdobeCreativeSDK#6]
Hi,

Do you know if any of the customization methods from the Aviary module are still available, such as:

aviary.setBackgroundColor(1,0,0,1);
aviary.setTopBarBackgroundColor(0,0.6,0,1);

These are referenced in the Aviary module in the example code on this page:

https://github.com/ghkim/AviaryModule

**Comment by kosso** [comment]
I looked at implementing that again, but it appears that an easy way to customise your Image Editor colours is to use a tool provided with the SDK download. 

In the SDK download zip is a folder /tools/MacOS/ImageSDKCustomizer  You can use this desktop OSX app to generate a custom bundle file to include with your app.

**Comment by bwilhelm** [comment]
Awesome - thank you for pointing that out!
